includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/Baseline.yaml
  - backbones/resnet12.yaml

modality: audio
mean_std_file: ./Auxiliary/Clean_Mean_Std.npy
class_per_split: ./Auxiliary/KOS_paper_splits.npy
ood: True


classifier:
  name: Baseline
  kwargs:
    inner_param:
      inner_optim:
        name: Adam
        kwargs:
          lr: 1e-3
      inner_train_iter: 100
      inner_batch_size: 4
    feat_dim: 4608
    num_class: 38

backbone:
  name: resnet12
  kwargs:
    keep_prob: 0.0
    avg_pool: True
    is_flatten: True
    maxpool_last2: True
    num_channels: 1


augment: true
augment_times: 1
augment_times_query: 1

batch_size: 128
classifier:
  kwargs:
    feat_dim: 12800
    inner_param:
      inner_batch_size: 4
      inner_optim:
        kwargs:
          dampening: 0.9
          lr: 0.01
          momentum: 0.9
          weight_decay: 0.001
        name: SGD
      inner_train_iter: 100
    num_class: 200
  name: Baseline
data_root: /root/SC/Results/KOS_1_alpha/KOS_1_alpha_spec
deterministic: true
device_ids: 1
episode_size: 1
epoch: 200
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Baseline.yaml
- backbones/resnet12.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 100
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
parallel_part:
- emb_func
port: 35001
pretrain_path: null
query_num: 5
rank: 0
result_root: ./results
resume: false
# resume_path: ./results/Baseline-miniImageNet--ravi-Conv64F-5-5-Dec-01-2021-06-52-22
save_interval: 50
save_part:
- emb_func
seed: 1
shot_num: 5
tag: null
tb_scale: 1.6666666666666667
test_episode: 600
test_epoch: 5
test_query: 5
test_shot: 5
test_way: 5
train_episode: 2000
use_memory: false
way_num: 5
workers: 32
epoch: 30