augment: false
augment_times: 1
augment_times_query: 1
backbone:
  name: Conv64F
  kwargs:
    is_flatten: True
    is_feature: False
    leaky_relu: False
    negative_slope: 0.2
    last_pool: True
    num_channels: 1
batch_size: 1
classifier:
  kwargs: null
  name: MetaBaselineKendall
data_root: /root/SC/Results/KOS_1_alpha/KOS_1_alpha_spec
dataloader_num: 1
deterministic: true
device_ids: 0
episode_size: 1
epoch: 10
# image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 10
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
  name: SGD
parallel_part:
- emb_func
- classifier
port: 31691
# pretrain_path: results/MetabaselineKendallPretrain-miniImageNet--ravi-resnet12-5-5-Jun-02-2024-20-21-31/checkpoints/emb_func_best.pth
query_num: 10
rank: 0
result_root: ./results
resume: false
save_interval: 5
save_part:
- emb_func
seed: 1
shot_num: 1
tag: null
tb_scale: 0.16666666666666666
test_episode: 600
test_epoch: 5
test_query: 10
test_shot: 1
test_way: 5
train_episode: 1000
use_memory: false
val_per_epoch: 1
warmup: 0
way_num: 5
workers: 8

modality: audio
mean_std_file: ./Auxiliary/Clean_Mean_Std.npy
class_per_split: ./Auxiliary/KOS_paper_splits.npy
ood: True
