includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/FEAT.yaml
  # - backbones/WRN.yaml

modality: audio
mean_std_file: ./Auxiliary/Clean_Mean_Std.npy
class_per_split: ./Auxiliary/KOS_paper_splits.npy
ood: True

classifier:
  name: FEAT
  kwargs:
    hdim: 1600
    temperature: 1.0
    temperature2: 1.0
    balance: 0.5
    mode: euclidean

backbone:
  name: Conv64F
  kwargs:
    is_flatten: True
    is_feature: False
    leaky_relu: False
    negative_slope: 0.2
    last_pool: True
    num_channels: 1

resume: True
pretrain_path: null

warmup: 0
batch_size: 128
deterministic: true
device_ids: 0
episode_size: 1
epoch: 30

log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 0.5
    step_size: 5
  name: StepLR

n_gpu: 1
optimizer:
  kwargs:
    lr: 0.05
    weight_decay: 0
  name: Adam
  other:
    emb_func: 0.01
parallel_part:
- emb_func
query_num: 10
rank: 0
result_root: ./results
resume: false
save_interval: 10
save_part:
- emb_func
seed: 1
shot_num: 1
tag: null
tb_scale: 8.333333333333334
test_episode: 600
test_epoch: 5
test_query: 10
test_shot: 1
test_way: 5
train_episode: 1000
use_memory: false
way_num: 5
data_root: /root/SC/Results/KOS_1_alpha/KOS_1_alpha_spec