# includes:
#   - headers/data.yaml
#   - headers/device.yaml
#   - headers/misc.yaml
#   - headers/model.yaml
#   - headers/optimizer.yaml

# way_num: 5
# shot_num: 1
# query_num: 10
# episode_size: 2
# train_episode: 2000
# test_episode: 600

# device_ids: 0
# n_gpu: 1
# epoch: 100
modality: audio
mean_std_file: ./Auxiliary/Clean_Mean_Std.npy
class_per_split: ./Auxiliary/KOS_paper_splits.npy
ood: True



# optimizer:
#   name: Adam
#   kwargs:
#     lr: 1e-3
#   other: ~

# backbone:
#   name: Conv64F
#   kwargs:
#     is_flatten: True
#     is_feature: False
#     leaky_relu: False
#     negative_slope: 0.2
#     last_pool: True
#     num_channels: 1

# classifier:
#   name: MAML
#   kwargs:
#     inner_param:
#       lr: 1e-2
#       train_iter: 5
#       test_iter: 10
#     feat_dim: 4608


# backbone:
#   name: resnet12
#   kwargs: ~

# classifier:
#   name: MAML
#   kwargs:
#     inner_param:
#       lr: 1e-2
#       train_iter: 5
#       test_iter: 10
#     feat_dim: 640


# backbone:
#   name: resnet18
#   kwargs: ~

# classifier:
#   name: MAML
#   kwargs:
#     inner_param:
#       lr: 1e-2
#       train_iter: 5
#       test_iter: 10
#     feat_dim: 512


# backbone:
#   name: WRN
#   kwargs:
#     depth: 28
#     widen_factor: 10

# classifier:
#   name: MAML
#   kwargs:
#     inner_param:
#       lr: 1e-2
#       train_iter: 5
#       test_iter: 10
#     feat_dim: 640


backbone:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
    num_channels: 1
  name: Conv64F
batch_size: 128
classifier:
  kwargs:
    feat_dim: 4608
    inner_param:
      lr: 0.01
      test_iter: 10
      train_iter: 5
  name: MAML
# data_root: /data/fewshot/miniImageNet--ravi
deterministic: true
device_ids: 0
episode_size: 4
epoch: 100
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/MAML.yaml
- backbones/resnet12.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 20
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
  other: null
parallel_part:
- emb_func
port: 28138
pretrain_path: null
query_num: 10
rank: 0
result_root: ./results
resume: false
save_interval: 10
save_part:
- emb_func
seed: 2147483647
shot_num: 1
tag: null
tb_scale: 3.3333333333333335
test_episode: 600
test_epoch: 5
test_query: 10
test_shot: 1
test_way: 5
train_episode: 2000
use_memory: false
way_num: 5
workers: 8
data_root: /root/SC/Results/KOS_clean_set/KOS_clean_set_spec

