includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - classifiers/R2D2.yaml

way_num: 5
shot_num: 1
query_num: 5
test_way: 5 # use ~ -> test_* = *_num
test_shot: 1
test_query: 5

modality: audio
mean_std_file: ./Auxiliary/Clean_Mean_Std.npy
class_per_split: ./Auxiliary/KOS_paper_splits.npy
ood: False

backbone:
  name: Conv64F
  kwargs:
    is_flatten: True
    is_feature: False
    leaky_relu: True
    negative_slope: 0.2
    last_pool: True
    num_channels: 1

# backbone:
#   name: resnet12
#   kwargs: ~

# backbone:
#   name: resnet18
#   kwargs: ~

# backbone:
#   name: WRN
#   kwargs:
#     depth: 28
#     widen_factor: 10
